default:
  prompt: '{readLines(system.file(''prompt/base.txt'', package = ''chattr''))}'
  max_data_files: 0
  max_data_frames: 0
  include_doc_contents: no
  include_history: yes
  provider: Open AI - Chat Completions
  path: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo
  model_arguments:
    temperature: 0.01
    max_tokens: 1000
    stream: yes
  system_msg: You are a helpful coding assistant
chat:
  prompt:
  - '{readLines(system.file(''prompt/base.txt'', package = ''chattr''))}'
  - For code output, use RMarkdown code chunks
  - Avoid all code chunk options
script:
  prompt:
  - '{readLines(system.file(''prompt/base.txt'', package = ''chattr''))}'
  - 'For any line that is not code, prefix with a: #'
  - Keep each line of explanations to no more than 80 characters
  - DO NOT use Markdown for the code
